import json
import logging
import os
import re

import chromadb
import ollama
from rank_bm25 import BM25Okapi

from app.core.config import settings

logger = logging.getLogger(__name__)

QUERY_PREFIX = "search_query: "  # nomic-embed-text asymmetric prefix, query side


def _tokenize(text: str) -> list[str]:
    return re.findall(r"[a-z0-9]+", text.lower())


class RetrievalService:
    """Loads the persisted vector store + chunk corpus once and serves hybrid
    (dense + BM25, RRF-fused) retrieval. Instantiated once at app startup."""

    def __init__(self):
        with open(settings.chunks_path, encoding="utf-8") as f:
            self.chunks = json.load(f)
        for c in self.chunks:
            # the source JSON was generated by the notebook pipeline with paths
            # relative to that project layout -- re-root by basename against this
            # backend's own images_dir so the backend is self-contained.
            image_path = c["metadata"].get("image_path")
            if image_path:
                c["metadata"]["image_path"] = os.path.join(settings.images_dir, os.path.basename(image_path))
        self.chunk_by_id = {c["id"]: c for c in self.chunks}

        client = chromadb.PersistentClient(path=settings.vector_store_path)
        self.collection = client.get_collection("attention_paper")

        self._bm25_ids = [c["id"] for c in self.chunks]
        self._bm25 = BM25Okapi([_tokenize(c["text"]) for c in self.chunks])

        logger.info("RetrievalService ready: %d chunks loaded from %s", len(self.chunks), settings.chunks_path)

    def embed_query(self, question: str) -> list[float]:
        resp = ollama.embed(model=settings.embed_model, input=QUERY_PREFIX + question)
        return resp.embeddings[0]

    def _dense_rank_all(self, query_vector: list[float]) -> list[dict]:
        res = self.collection.query(query_embeddings=[query_vector], n_results=len(self.chunks))
        return [{"id": id_, "distance": dist} for id_, dist in zip(res["ids"][0], res["distances"][0])]

    def _bm25_rank_all(self, question: str) -> list[dict]:
        scores = self._bm25.get_scores(_tokenize(question))
        ranked = sorted(zip(self._bm25_ids, scores), key=lambda x: -x[1])
        return [{"id": id_, "score": float(s)} for id_, s in ranked]

    def hybrid_retrieve(self, question: str, k: int | None = None) -> tuple[list[dict], float]:
        """Returns (top-k chunks, best dense distance). The distance is the scope
        signal used by app.services.intent to reject off-topic questions before any
        VLM/LLM call is made."""
        k = k or settings.top_k
        query_vector = self.embed_query(question)
        dense = self._dense_rank_all(query_vector)
        bm25 = self._bm25_rank_all(question)
        dense_rank = {d["id"]: i + 1 for i, d in enumerate(dense)}
        bm25_rank = {d["id"]: i + 1 for i, d in enumerate(bm25)}

        fused = []
        for cid in dense_rank:
            rd, rb = dense_rank[cid], bm25_rank[cid]
            fused.append({
                "id": cid,
                "fused_score": 1 / (settings.rrf_k + rd) + 1 / (settings.rrf_k + rb),
            })
        fused.sort(key=lambda x: -x["fused_score"])
        top = fused[:k]
        best_distance = dense[0]["distance"]

        logger.info(
            "retrieved top-%d for %r: %s (best_distance=%.4f)",
            k, question[:60], [t["id"] for t in top], best_distance,
        )
        return [self.chunk_by_id[t["id"]] for t in top], best_distance
